apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "ct_admin"
  DB_NAME: "geoconnections"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  KAFKA_SERVER: "my-release-kafka-0.my-release-kafka-headless.default.svc.cluster.local:9092"
  PERSON_API_ADRESS: "localhost:30001"
  CONNECTION_API_ADRESS: "localhost:30004"
  LOCATION_INGESTION_API_ADRESS: "localhost:30003"
  LOCATION_PROCESSOR_API_ADRESS: "localhost:30002"
metadata:
  name: db-env