apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "ct_admin"
  DB_NAME: "geoconnections"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  KAFKA_CFG_ZOOKEEPER_CONNECT: "localhost:30006"
  KAFKA_SERVER: "localhost:30005"
  PERSON_API_ADRESS: "localhost:30001"
  CONNECTION_API_ADRESS: "localhost:30004"
  LOCATION_INGESTION_API_ADRESS: "localhost:30003"
  LOCATION_PROCESSOR_API_ADRESS: "localhost:30002"
metadata:
  name: db-env