apiVersion: v1
kind: Service
metadata:
  labels:
    service: location_processor_api
  name: location_processor_api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30002
  selector:
    service: location_processor_api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location_processor_api
  name: location_processor_api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location_processor_api
  template:
    metadata:
      labels:
        service: location_processor_api
    spec:
      containers:
      - image: abszissex/location_processor_api:latest
        name: location_processor_api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: KAFKA_SERVER
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_SERVER
      restartPolicy: Always
