apiVersion: v1
kind: Service
metadata:
  labels:
    service: location_ingestion_api
  name: location_ingestion_api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30003
  selector:
    service: location_ingestion_api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: location_ingestion_api
  name: location_ingestion_api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: location_ingestion_api
  template:
    metadata:
      labels:
        service: location_ingestion_api
    spec:
      containers:
      - image: abszissex/location_ingestion_api:latest
        name: location_ingestion_api
        imagePullPolicy: Always
        env:
        - name: KAFKA_SERVER
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: KAFKA_SERVER
      restartPolicy: Always
