apiVersion: v1
kind: Service
metadata:
  labels:
    service: connection_api
  name: connection_api
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30004
  selector:
    service: connection_api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: connection_api
  name: connection_api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: connection_api
  template:
    metadata:
      labels:
        service: connection_api
    spec:
      containers:
      - image: abszissex/connection_api:latest
        name: connection_api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
        - name: PERSON_API_ADRESS
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: PERSON_API_ADRESS
      restartPolicy: Always
